name = "vlessid"
main = "_worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[[routes]]
pattern = "vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.vcip.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "business.blibli.com.vlessid.pages.dev"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.vlessid.pages.dev"
custom_domain = true
